(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['body'] = template({"compiler":[8,">= 4.3.0"],"main":function(container,depth0,helpers,partials,data) {
    var stack1, helper, alias1=depth0 != null ? depth0 : (container.nullContext || {}), alias2=container.hooks.helperMissing, alias3="function", alias4=container.escapeExpression, lookupProperty = container.lookupProperty || function(parent, propertyName) {
        if (Object.prototype.hasOwnProperty.call(parent, propertyName)) {
          return parent[propertyName];
        }
        return undefined
    };

  return "<a class=\"logo\" href=\"/wallets\">"
    + alias4(((helper = (helper = lookupProperty(helpers,"wallets") || (depth0 != null ? lookupProperty(depth0,"wallets") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"wallets","hash":{},"data":data,"loc":{"start":{"line":1,"column":32},"end":{"line":1,"column":43}}}) : helper)))
    + "</a>\r\n<svg class=\"hamburger\">\r\n    <path\r\n        d=\"M4 10h24a2 2 0 0 0 0-4H4a2 2 0 0 0 0 4zm24 4H4a2 2 0 0 0 0 4h24a2 2 0 0 0 0-4zm0 8H4a2 2 0 0 0 0 4h24a2 2 0 0 0 0-4z\" />\r\n</svg>\r\n<BiiP></BiiP>\r\n<header>\r\n    <svg class=\"close\" viewBox=\"0 0 128 128\">\r\n        <path d=\"M64 0a64 64 0 1 0 64 64A64.07 64.07 0 0 0 64 0Zm0 122a58 58 0 1 1 58-58 58.07 58.07 0 0 1-58 58Z\" />\r\n        <path\r\n            d=\"M92.12 35.79a3 3 0 0 0-4.24 0L64 59.75l-23.87-24A3 3 0 0 0 35.88 40l23.88 24-23.88 24a3 3 0 0 0 4.25 4.24L64 68.25l23.88 24A3 3 0 0 0 92.13 88L68.24 64l23.89-24a3 3 0 0 0-.01-4.21Z\" />\r\n    </svg>\r\n    <nav id=\"nav\">\r\n        <a href=\"/\"><img src=\"/svgs/home.svg\" loading=\"lazy\" alt=\"Homepage\" />"
    + alias4(((helper = (helper = lookupProperty(helpers,"home") || (depth0 != null ? lookupProperty(depth0,"home") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"home","hash":{},"data":data,"loc":{"start":{"line":14,"column":78},"end":{"line":14,"column":86}}}) : helper)))
    + "</a>\r\n        <a href=\"/presale\"><img src=\"/svgs/gratitude-token-logo.svg\" loading=\"lazy\"\r\n                alt=\"Public Presale\" />"
    + alias4(((helper = (helper = lookupProperty(helpers,"presale") || (depth0 != null ? lookupProperty(depth0,"presale") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"presale","hash":{},"data":data,"loc":{"start":{"line":16,"column":39},"end":{"line":16,"column":50}}}) : helper)))
    + "</a>\r\n        <a href=\"/tokenomics\"><img src=\"/svgs/tokenomics.svg\" loading=\"lazy\" alt=\"Tokenomics\" />"
    + alias4(((helper = (helper = lookupProperty(helpers,"tokenomics") || (depth0 != null ? lookupProperty(depth0,"tokenomics") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"tokenomics","hash":{},"data":data,"loc":{"start":{"line":17,"column":96},"end":{"line":17,"column":110}}}) : helper)))
    + "</a>\r\n        <a href=\"/white-paper\"><img src=\"/svgs/pdf-icon.svg\" loading=\"lazy\" alt=\"White Paper\" />"
    + alias4(((helper = (helper = lookupProperty(helpers,"whitePaper") || (depth0 != null ? lookupProperty(depth0,"whitePaper") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"whitePaper","hash":{},"data":data,"loc":{"start":{"line":18,"column":96},"end":{"line":18,"column":110}}}) : helper)))
    + "</a>\r\n        <a id=\"languageSelect\"><i>"
    + alias4(((helper = (helper = lookupProperty(helpers,"lang-code") || (depth0 != null ? lookupProperty(depth0,"lang-code") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"lang-code","hash":{},"data":data,"loc":{"start":{"line":19,"column":34},"end":{"line":19,"column":47}}}) : helper)))
    + "</i>"
    + alias4(((helper = (helper = lookupProperty(helpers,"language") || (depth0 != null ? lookupProperty(depth0,"language") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"language","hash":{},"data":data,"loc":{"start":{"line":19,"column":51},"end":{"line":19,"column":63}}}) : helper)))
    + "</a>\r\n    </nav>\r\n</header>\r\n\r\n<div class=\"wrapper-wide\" style=\"background: none\">\r\n    <div class=\"content-wide\" style=\"text-align: center; background: none\">\r\n        <h1 style=\"text-align: center\"><img style=\"width: 32px; height: 32px; vertical-align: bottom\" src=\"/svgs/wallet.svg\" alt=\"wallet\" /> "
    + alias4(((helper = (helper = lookupProperty(helpers,"wallets") || (depth0 != null ? lookupProperty(depth0,"wallets") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"wallets","hash":{},"data":data,"loc":{"start":{"line":25,"column":141},"end":{"line":25,"column":152}}}) : helper)))
    + "</h1>\r\n        <br>\r\n        <p style=\"display: block; font-size: 14px\">"
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"phrase1") || (depth0 != null ? lookupProperty(depth0,"phrase1") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"phrase1","hash":{},"data":data,"loc":{"start":{"line":27,"column":51},"end":{"line":27,"column":64}}}) : helper))) != null ? stack1 : "")
    + "<br><br>\r\n        <b style=\"color: var(--logoColor)\">"
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"phrase2") || (depth0 != null ? lookupProperty(depth0,"phrase2") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"phrase2","hash":{},"data":data,"loc":{"start":{"line":28,"column":43},"end":{"line":28,"column":56}}}) : helper))) != null ? stack1 : "")
    + "</b></p><br>\r\n        <div class=\"grid-1-2\">\r\n            <div>\r\n                <h2><img style=\"width: 100px; height: 100px; display: block; margin: 23px auto\" src=\"/wallets/img/proton-xpr-logo.svg\"/>WebAuth</h2>\r\n                <p><span style=\"color: #999999; font-size: 12px\">WebAuth "
    + alias4(((helper = (helper = lookupProperty(helpers,"available") || (depth0 != null ? lookupProperty(depth0,"available") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"available","hash":{},"data":data,"loc":{"start":{"line":32,"column":73},"end":{"line":32,"column":86}}}) : helper)))
    + "</span><br>\r\n                <img style=\"width: 120px; height: 40px\" src=\"https://www.logo.wine/a/logo/Google_Play/Google_Play-Logo.wine.svg\"/> <img style=\"width: 40px; height: 40px\" src=\"https://www.logo.wine/a/logo/Apple_Inc./Apple_Inc.-White-Logo.wine.svg\"/>\r\n                <br>\r\n                <a href=\"https://play.google.com/store/apps/details?id=com.metallicus.webauth\" target=\"_blank\" class=\"color-blue\">Android</a> | <a href=\"https://apps.apple.com/us/app/webauth/id1594500069\" target=\"_blank\" class=\"color-blue\">iOS</a> | <a href=\"https://webauth.com/start\" target=\"_blank\" class=\"color-blue\">Web</a>\r\n                </p>\r\n            </div>\r\n\r\n            <div>\r\n                <h2><img style=\"width: 100px; height: 100px; display: block; margin: 23px auto\" src=\"/wallets/img/anchor-wallet.png\"/>Anchor</h2>\r\n                <p><span style=\"color: #999999; font-size: 12px\">Anchor "
    + alias4(((helper = (helper = lookupProperty(helpers,"available") || (depth0 != null ? lookupProperty(depth0,"available") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"available","hash":{},"data":data,"loc":{"start":{"line":41,"column":72},"end":{"line":41,"column":85}}}) : helper)))
    + "</span><br>\r\n                Windows | macOS | Linux | iOS | Android\r\n                <br><br>\r\n                <a href=\"https://greymass.com/en/anchor/download\" target=\"_blank\" class=\"color-blue\">Greymass.com</a> "
    + alias4(((helper = (helper = lookupProperty(helpers,"anchor_title") || (depth0 != null ? lookupProperty(depth0,"anchor_title") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"anchor_title","hash":{},"data":data,"loc":{"start":{"line":44,"column":118},"end":{"line":44,"column":134}}}) : helper)))
    + "\r\n                </p>\r\n            </div>\r\n        </div>\r\n        "
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"recruitment") || (depth0 != null ? lookupProperty(depth0,"recruitment") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"recruitment","hash":{},"data":data,"loc":{"start":{"line":48,"column":8},"end":{"line":48,"column":25}}}) : helper))) != null ? stack1 : "")
    + "\r\n        <div class='shareThis'>"
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"share") || (depth0 != null ? lookupProperty(depth0,"share") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"share","hash":{},"data":data,"loc":{"start":{"line":49,"column":31},"end":{"line":49,"column":42}}}) : helper))) != null ? stack1 : "")
    + "</div>\r\n        <div class='sharethis-inline-share-buttons'></div>\r\n        "
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"footer_nav") || (depth0 != null ? lookupProperty(depth0,"footer_nav") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"footer_nav","hash":{},"data":data,"loc":{"start":{"line":51,"column":8},"end":{"line":51,"column":24}}}) : helper))) != null ? stack1 : "")
    + "\r\n        <footer>\r\n            "
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"footer") || (depth0 != null ? lookupProperty(depth0,"footer") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"footer","hash":{},"data":data,"loc":{"start":{"line":53,"column":12},"end":{"line":53,"column":24}}}) : helper))) != null ? stack1 : "")
    + "\r\n            "
    + ((stack1 = ((helper = (helper = lookupProperty(helpers,"copy") || (depth0 != null ? lookupProperty(depth0,"copy") : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"copy","hash":{},"data":data,"loc":{"start":{"line":54,"column":12},"end":{"line":54,"column":22}}}) : helper))) != null ? stack1 : "")
    + "\r\n        </footer>\r\n    </div>\r\n</div>";
},"useData":true});
})();